cargo-features = ["edition2021"]

[package]
name = "riscv"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
tcp = ["smoltcp"]
default = ["tcp"]

[dependencies]
log = "0.4"
riscv = "0.10"
# opensbi-rt = { git = "https://github.com/rcore-os/opensbi-rt.git", rev = "1308cc5" }
opensbi-rt = { git = "https://github.com/rcore-os/opensbi-rt.git", rev = "abdfeb72" }
device_tree = { git = "https://github.com/rcore-os/device_tree-rs", rev = "2fa8411" }
virtio-drivers = { path = "../.." }
lazy_static = { version = "1.4", features = ["spin_no_std"] }

[workspace]
members = ["examples/riscv"]

[dependencies.smoltcp]
version = "0.9.1"
optional = true
default-features = false
features = [
    "alloc",
    "log",             # no std
    "medium-ethernet",
    "proto-ipv4",
    "socket-raw",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
]
